# Generated by Django 4.2.2 on 2023-06-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespol',
            name='b_stracone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zespol',
            name='b_zdobyte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zespol',
            name='l_meczy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zespol',
            name='porazki',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zespol',
            name='remisy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zespol',
            name='zwyciestwa',
            field=models.IntegerField(default=0),
        ),
    ]
