# Generated by Django 4.2.2 on 2023-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tabela', '0002_zespol_b_stracone_zespol_b_zdobyte_zespol_l_meczy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespol',
            name='punkty',
            field=models.IntegerField(default=0),
        ),
    ]
